### ISSUE TITLE
The flag in home page is upside-down 

### ISSUE THREAD

**Issue by Haadka** [Code4Somaliland/somaliland-profile#1]
Issue:

The flag is upside-down 

![20210803_195034](https://user-images.githubusercontent.com/1536498/127995907-f8fa6650-86ca-4596-9e2a-79fd603a7cbe.jpg)

AC

The flag should be flipped on the home page so that it match Somaliland's flag

**Comment by janogale** [comment]
I have fixed this with 8fb8dc9adf498e207df883678aa86b08db6a4ebe
